### ISSUE TITLE
502/504 errors hosting frontend with IIS

### ISSUE THREAD

**Issue by savage8811** [davidfowl/YarpTunnelDemo#10]
first, thank you for sharing this project. :)

I tried to deploy the frontend on a windows server (ISS) to share a local website. The first document request works, but loading the css/js-files of the website stuck after 5-6 requests and fail after some seconds with error 502 and 504.
If I start the kestrel direct on the same machine without IIS it works like a charm.
Is it a bad idea hosting kestrel&yarp with IIS?

TY

**Comment by davidfowl** [comment]
You're only hosting the front end YARP on IIS right? The backend is using Kestrel? Are you using websockets or http2?

**Comment by savage8811** [comment]
Yes you're right. Some more details.
- frontend yarp hosted on IIS10 (win2016server)
- backend launched locally using kestrel (destination also launched on localhost, razor-website, kestrel)
- using http2, no websockets

If I open now open the frontend (https://remote.MYDOMAIN.com/), it result into loading the page und some follow-up requests, but some styles/js/images stuck: 
![remote conrox](https://user-images.githubusercontent.com/1926297/220284510-7fb73930-9152-4538-beb2-6d82473ad7fb.png)
And result into a 502 error 
![remote conrox com-2](https://user-images.githubusercontent.com/1926297/220284536-c6dba3cf-b54f-410b-9f5c-2b6bef5ed620.png)

If I launch frontend kestrel on the same server (on a different port because 443 used by IIS for other websites), it work like a charm. Opening https://remote.MYDOMAIN.com:5001/ 
![5001](https://user-images.githubusercontent.com/1926297/220284564-0352e5e6-bc26-40b9-aae5-95f3c0303967.png)

I also tried different destinations with same results.

**Comment by rajadev2019** [comment]
Same problem with me, please prioritize this one. I am hosting APIs and using http2. The first request works most of the time, from 2nd request onwards mostly it gets 502, after few seconds it again works. I tried changing the versions from .NET 8.0 to 6.0 but still it didn't work.

Code: https://github.com/rajadev2019/YarpTunnelDemo/tree/XenSolution_POC
Test URL: https://apireverseproxy.xensolution.com/APIOne/response & https://apireverseproxy.xensolution.com/APITwo/response

Please help, also Please let me know if you need any additional input for this.
https://www.linkedin.com/in/ranajit-koley/
https://x.com/rajaranajitlove

**Comment by davidfowl** [comment]
> please prioritize this one

Most helpful thing would be a reliable repro.

**Comment by rajadev2019** [comment]
<img width="1341" alt="Postman Performance Screenshot" src="https://github.com/user-attachments/assets/22f21b0d-16f9-405e-b558-0f0af194403c">
Thanks a lot for your quick response.

Front end Errors:

apireverseproxy.xensolution.com is currently unable to handle this request.
HTTP ERROR 502

This page isn’t working
apireverseproxy.xensolution.com took too long to respond.
HTTP ERROR 504


If you please click on either/both links and refresh couple of times, you will see the error.

Some errors logs I got now is:

Windows application event entries for startup diagnostics test. Website 'apireverseproxy.somee.com'
Time: 9/1/2024 1:18:44 AM -05:00 (US Central time)
Source: .NET Runtime
Event ID: 1000
level: Warning
Category: Yarp.ReverseProxy.Forwarder.HttpForwarder
EventId: 48
SpanId: 590e10df4693eb61
TraceId: 25b8089516aa2c06ca047772ff666c51
ParentId: d168eab9f09fe0d5
RequestId: 40002fe1-0002-f200-b63f-84710c7967bb
RequestPath: /

RequestTimedOut: The request timed out before receiving a response.

Exception: 
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.TimeoutException: A connection could not be established within the configured ConnectTimeout.
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.CreateConnectTimeoutException(OperationCanceledException oce)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.CancellationCleanupLogic()
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception exception)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.CancellationCleanupLogic()
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception exception)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.CancellationCleanupLogic()
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception exception)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.CancellationCleanupLogic()
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception exception)
   at TunnelClientFactory.<>c__DisplayClass2_0.<<ConfigureHandler>b__1>d.MoveNext() in /Users/raja/Data/WORK/Code/YarpTunnelDemo/Frontend/Tunnel/TunnelClientFactory.cs:line 66
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.ThreadPool.<>c.<.cctor>b__61_0(Object state)
   at System.Threading.Channels.AsyncOperation`1.SetCompletionAndInvokeContinuation()
   at System.Threading.Channels.AsyncOperation`1.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)
Time: 9/1/2024 1:18:41 AM -05:00 (US Central time)
Source: .NET Runtime
Event ID: 1000
level: Warning
Category: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager
EventId: 35

No XML encryptor configured. Key {2d05b8a7-bce4-4d46-b053-f104cf5a8021} may be persisted to storage in unencrypted form.
Time: 9/1/2024 1:18:41 AM -05:00 (US Central time)
Source: IIS AspNetCore Module V2
Event ID: 1032
level: Information
Application 'd:\DZHosts\LocalUser\apireverseproxy\www.apireverseproxy.somee.com\' started successfully.
Time: 9/1/2024 1:18:40 AM -05:00 (US Central time)
Source: .NET Runtime
Event ID: 1000
level: Warning
Category: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository
EventId: 50

Using an in-memory repository. Keys will not be persisted to storage.
Time: 9/1/2024 1:18:40 AM -05:00 (US Central time)
Source: .NET Runtime
Event ID: 1000
level: Warning
Category: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager
EventId: 59

Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
Time: 9/1/2024 1:18:38 AM -05:00 (US Central time)
Source: IIS AspNetCore Module V2
Event ID: 1005
level: Warning
Failed to gracefully shutdown application 'MACHINE/WEBROOT/APPHOST/APIREVERSEPROXY.SOMEE.COM'.





Some more errors I got is:

Windows application event entries for startup diagnostics test. Website 'apireverseproxy.somee.com'
Time: 9/1/2024 1:26:01 AM -05:00 (US Central time)
Source: .NET Runtime
Event ID: 1000
level: Error
Category: Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer
EventId: 3
SpanId: 322a63a0038846c3
TraceId: a51e248c1ed405f5270db42d64cfa18d
ParentId: 5053f5f55bdc1b87
RequestId: 4000273b-0002-a000-b63f-84710c7967bb
RequestPath: /APITwo/response

Unexpected exception in "IISHttpContext.ReadBody".

Exception: 
System.InvalidOperationException: Writing is not allowed after writer was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
   at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.GetMemory(Int32 sizeHint)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadBody()
Time: 9/1/2024 1:26:01 AM -05:00 (US Central time)
Source: .NET Runtime
Event ID: 1000
level: Warning
Category: Yarp.ReverseProxy.Forwarder.HttpForwarder
EventId: 48
SpanId: 513be6ae6bf273f4
TraceId: 0f69ca5d5e930695cc1e3756cc2d015a
ParentId: 0000000000000000
RequestId: 40003b9d-0001-7700-b63f-84710c7967bb
RequestPath: /favicon.ico

RequestCanceled: The request was canceled before receiving a response.

Exception: 
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.InvalidOperationException: Concurrent reads or writes are not supported.
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1 memory, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)
Time: 9/1/2024 1:26:01 AM -05:00 (US Central time)
Source: .NET Runtime
Event ID: 1000
level: Warning
Category: Yarp.ReverseProxy.Forwarder.HttpForwarder
EventId: 48
SpanId: aff5cb0100c78553
TraceId: 733d71700de0fdab8e9245753e08b9d2
ParentId: 4a66fc94abc02bc0
RequestId: 4000024d-0003-9900-b63f-84710c7967bb
RequestPath: /

Request: An error was encountered before receiving a response.

Exception: 
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.InvalidOperationException: Concurrent reads or writes are not supported.
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1 memory, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)
Time: 9/1/2024 1:26:01 AM -05:00 (US Central time)
Source: .NET Runtime
Event ID: 1000
level: Warning
Category: Yarp.ReverseProxy.Forwarder.HttpForwarder
EventId: 48
SpanId: 5bbed3440612d991
TraceId: 5b48b6a7524540f0c78977d39bd669c4
ParentId: 0000000000000000
RequestId: 4000024b-0003-9900-b63f-84710c7967bb
RequestPath: /favicon.ico

RequestCanceled: The request was canceled before receiving a response.

Exception: 
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: The client has disconnected
 ---> System.Runtime.InteropServices.COMException (0x800704CD): An operation was attempted on a nonexistent network connection. (0x800704CD)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOOperation.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadBody()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1 memory, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)
Time: 9/1/2024 1:26:01 AM -05:00 (US Central time)
Source: IIS AspNetCore Module V2
Event ID: 1033
level: Information
Application 'MACHINE/WEBROOT/APPHOST/APIREVERSEPROXY.SOMEE.COM' has shutdown.
Time: 9/1/2024 1:25:53 AM -05:00 (US Central time)
Source: .NET Runtime
Event ID: 1000
level: Warning
Category: Yarp.ReverseProxy.Forwarder.HttpForwarder
EventId: 48
SpanId: dcd7b6da12fc5463
TraceId: 2eb66d7af0fb91c73771ba9b0e19c699
ParentId: 0000000000000000
RequestId: 400041c7-0001-5200-b63f-84710c7967bb
RequestPath: /APIOne/response

RequestTimedOut: The request timed out before receiving a response.

Exception: 
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: The client has disconnected
 ---> System.Runtime.InteropServices.COMException (0x800704CD): An operation was attempted on a nonexistent network connection. (0x800704CD)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOOperation.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadBody()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1 memory, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)
